# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='StaffMembers',
        ),
        migrations.AlterModelOptions(
            name='staffmembers',
            options={'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
    ]
