# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20171031_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmembers',
            name='title',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching'), ('Other', 'Other')], default=('Other', 'Other'), max_length=100),
        ),
        migrations.AlterField(
            model_name='staffmembers',
            name='blurb',
            field=models.TextField(blank=True, default='\n    THis is a test\n'),
        ),
    ]
