# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20171031_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmembers',
            name='blurb',
            field=models.TextField(blank=True, default='Here you can write a bit about yourself. You can just write regular text, but you are also able to use basic HTML to spice up your blurb. \nHere are some examples:\n\n\n\n    <b>Bold Text</b>\n\n    <i>Italics</i>\n\n\nHeadings:\n    <h1>Heading 1</h1> <!-- Largest -->\n    <h2>Heading 2</h2>\n    <h3>Heading 3</h3>\n    <h4>Heading 4</h4>\n    <h5>Heading 5</h5>\n    <h6>Heading 6</h6> <!-- Smallest -->\n\nNumbered List:\n    <ol>\n        <li>List Item 1</li>\n        <li>List Item 2</li>\n        <li>...</li>\n        <li>List Item N</li>\n    </ol>\n\nDot Point List:\n    <ul>\n        <li>List Item 1</li>\n        <li>List Item 2</li>\n        <li>...</li>\n        <li>List Item N</li>\n    </ul>\n\n'),
        ),
    ]
