# Generated by Django 2.0 on 2018-02-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20171101_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmembers',
            name='blurb',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='staffmembers',
            name='role',
            field=models.CharField(help_text='e.g. Art Therapist, Sports Coordinator, etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffmembers',
            name='title',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching'), ('Other', 'Other')], default=('Executive', 'Executive'), max_length=100),
        ),
    ]
