# Generated by Django 2.0 on 2018-02-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20180202_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmembers',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
