"""
Django settings for centennial_park_school project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import datetime
from datetime import time
from .base import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "$o^(5t%k8%a&0a05_6z^kc_)w^y=o+c*c0p)t9r5!h&lq2a-xp"
RECAPTCHA_SECRET_KEY = '6LdgLlgUAAAAACbur18uMDwaOzsv8n91_oa3xj-Z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS += ['webapp-384830.pythonanywhere.com', 'www.centennialparkschool.nsw.edu.au']


# Application definition

INSTALLED_APPS = [
    'apps.main',
    'apps.contact',
    'apps.staff',
    'apps.console',
    'apps.behaviour',
    'apps.api',
    'apps.downloads',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'centennial_park_school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'main/templates/',
            'gallery/templates/',
            'contact/templates/',
            'staff/templates/',
            'tracking/',
            'tracking/templates',
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.media',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, '..', 'cps_external', 'deployment_db.sqlite3'),
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '..', 'cps_external', 'staticfiles')


MEDIA_ROOT = os.path.join(BASE_DIR, '..', 'cps_external', 'media')
MEDIA_URL = '/media/'


CONTACT_EMAILS = [
    'sam.scheding1@det.nsw.edu.au',
    'samscheding@gmail.com',
    'centennial-s.school@det.nsw.edu.au',
    'david.lomas1@det.nsw.edu.au',
]

EMAIL_HOST = "in-v3.mailjet.com"
EMAIL_HOST_USER = "4973c25f516c04a4434a0b2c3375dca0"
EMAIL_HOST_PASSWORD = 'c863b3b59c557cfade23c5d259807a1b'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
