# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20171019_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name_plural': 'gallery_images'},
        ),
        migrations.AlterModelTable(
            name='galleryimage',
            table='gallery_image',
        ),
    ]
