# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20171020_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
