# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20171020_0306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name_plural': 'Gallery Images'},
        ),
    ]
