# Generated by Django 2.0.3 on 2018-04-18 01:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviourTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('term', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('year', models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('b1', models.CharField(blank=True, max_length=256)),
                ('b2', models.CharField(blank=True, max_length=256)),
                ('monday_points', models.IntegerField(blank=True)),
                ('monday_attended', models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended')], default=0)),
                ('monday_arrived', models.TimeField(blank=True, choices=[(datetime.time(9, 0), datetime.time(9, 0)), (datetime.time(9, 30), datetime.time(9, 30)), (datetime.time(10, 0), datetime.time(10, 0)), (datetime.time(10, 30), datetime.time(10, 30)), (datetime.time(11, 0), datetime.time(11, 0)), (datetime.time(11, 30), datetime.time(11, 30)), (datetime.time(12, 0), datetime.time(12, 0)), (datetime.time(12, 30), datetime.time(12, 30)), (datetime.time(13, 0), datetime.time(13, 0)), (datetime.time(13, 30), datetime.time(13, 30)), (datetime.time(14, 0), datetime.time(14, 0)), (datetime.time(14, 30), datetime.time(14, 30))], default=(datetime.time(9, 0), datetime.time(9, 0)))),
                ('tuesday_points', models.IntegerField(blank=True)),
                ('tuesday_attended', models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended')], default=0)),
                ('tuesday_arrived', models.TimeField(blank=True, choices=[(datetime.time(9, 0), datetime.time(9, 0)), (datetime.time(9, 30), datetime.time(9, 30)), (datetime.time(10, 0), datetime.time(10, 0)), (datetime.time(10, 30), datetime.time(10, 30)), (datetime.time(11, 0), datetime.time(11, 0)), (datetime.time(11, 30), datetime.time(11, 30)), (datetime.time(12, 0), datetime.time(12, 0)), (datetime.time(12, 30), datetime.time(12, 30)), (datetime.time(13, 0), datetime.time(13, 0)), (datetime.time(13, 30), datetime.time(13, 30)), (datetime.time(14, 0), datetime.time(14, 0)), (datetime.time(14, 30), datetime.time(14, 30))], default=(datetime.time(9, 0), datetime.time(9, 0)))),
                ('wednesday_points', models.IntegerField(blank=True)),
                ('wednesday_attended', models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended')], default=0)),
                ('wednesday_arrived', models.TimeField(blank=True, choices=[(datetime.time(9, 0), datetime.time(9, 0)), (datetime.time(9, 30), datetime.time(9, 30)), (datetime.time(10, 0), datetime.time(10, 0)), (datetime.time(10, 30), datetime.time(10, 30)), (datetime.time(11, 0), datetime.time(11, 0)), (datetime.time(11, 30), datetime.time(11, 30)), (datetime.time(12, 0), datetime.time(12, 0)), (datetime.time(12, 30), datetime.time(12, 30)), (datetime.time(13, 0), datetime.time(13, 0)), (datetime.time(13, 30), datetime.time(13, 30)), (datetime.time(14, 0), datetime.time(14, 0)), (datetime.time(14, 30), datetime.time(14, 30))], default=(datetime.time(9, 0), datetime.time(9, 0)))),
                ('thursday_points', models.IntegerField(blank=True)),
                ('thursday_attended', models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended')], default=0)),
                ('thursday_arrived', models.TimeField(blank=True, choices=[(datetime.time(9, 0), datetime.time(9, 0)), (datetime.time(9, 30), datetime.time(9, 30)), (datetime.time(10, 0), datetime.time(10, 0)), (datetime.time(10, 30), datetime.time(10, 30)), (datetime.time(11, 0), datetime.time(11, 0)), (datetime.time(11, 30), datetime.time(11, 30)), (datetime.time(12, 0), datetime.time(12, 0)), (datetime.time(12, 30), datetime.time(12, 30)), (datetime.time(13, 0), datetime.time(13, 0)), (datetime.time(13, 30), datetime.time(13, 30)), (datetime.time(14, 0), datetime.time(14, 0)), (datetime.time(14, 30), datetime.time(14, 30))], default=(datetime.time(9, 0), datetime.time(9, 0)))),
                ('friday_points', models.IntegerField(blank=True)),
                ('friday_attended', models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended')], default=0)),
                ('friday_arrived', models.TimeField(blank=True, choices=[(datetime.time(9, 0), datetime.time(9, 0)), (datetime.time(9, 30), datetime.time(9, 30)), (datetime.time(10, 0), datetime.time(10, 0)), (datetime.time(10, 30), datetime.time(10, 30)), (datetime.time(11, 0), datetime.time(11, 0)), (datetime.time(11, 30), datetime.time(11, 30)), (datetime.time(12, 0), datetime.time(12, 0)), (datetime.time(12, 30), datetime.time(12, 30)), (datetime.time(13, 0), datetime.time(13, 0)), (datetime.time(13, 30), datetime.time(13, 30)), (datetime.time(14, 0), datetime.time(14, 0)), (datetime.time(14, 30), datetime.time(14, 30))], default=(datetime.time(9, 0), datetime.time(9, 0)))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Student')),
            ],
            options={
                'db_table': 'tracking_behaviourtracking',
            },
        ),
    ]
