# Generated by Django 2.1 on 2018-08-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviourtracking',
            name='friday_attended',
            field=models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended'), (6, 'Public Holiday')], default=0),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='monday_attended',
            field=models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended'), (6, 'Public Holiday')], default=0),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='thursday_attended',
            field=models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended'), (6, 'Public Holiday')], default=0),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='tuesday_attended',
            field=models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended'), (6, 'Public Holiday')], default=0),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='wednesday_attended',
            field=models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended'), (6, 'Public Holiday')], default=0),
        ),
    ]
