# Generated by Django 2.0.2 on 2018-05-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviourtracking',
            name='friday_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='monday_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='thursday_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='tuesday_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='wednesday_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
