# Generated by Django 2.0 on 2018-03-02 00:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviourTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('term', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('year', models.IntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('b1', models.CharField(blank=True, max_length=256)),
                ('b2', models.CharField(blank=True, max_length=256)),
                ('monday_points', models.IntegerField(blank=True, default=100)),
                ('monday_attended', models.IntegerField(blank=True, choices=[(0, 'Attended'), (1, 'Absent (Explained)'), (2, 'Absent (Unexplained'), (3, 'Integrating')], default=0)),
                ('monday_arrived', models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 AM'), (datetime.time(9, 30), '9:30 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(10, 30), '10:30 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(13, 30), '1:30 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(14, 30), '2:30 PM')], default=(datetime.time(9, 0), '9:00 AM'))),
                ('tuesday_points', models.IntegerField(blank=True, default=100)),
                ('tuesday_attended', models.IntegerField(blank=True, choices=[(0, 'Attended'), (1, 'Absent (Explained)'), (2, 'Absent (Unexplained'), (3, 'Integrating')], default=0)),
                ('tuesday_arrived', models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 AM'), (datetime.time(9, 30), '9:30 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(10, 30), '10:30 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(13, 30), '1:30 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(14, 30), '2:30 PM')], default=(datetime.time(9, 0), '9:00 AM'))),
                ('wednesday_points', models.IntegerField(blank=True, default=100)),
                ('wednesday_attended', models.IntegerField(blank=True, choices=[(0, 'Attended'), (1, 'Absent (Explained)'), (2, 'Absent (Unexplained'), (3, 'Integrating')], default=0)),
                ('wednesday_arrived', models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 AM'), (datetime.time(9, 30), '9:30 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(10, 30), '10:30 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(13, 30), '1:30 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(14, 30), '2:30 PM')], default=(datetime.time(9, 0), '9:00 AM'))),
                ('thursday_points', models.IntegerField(blank=True, default=100)),
                ('thursday_attended', models.IntegerField(blank=True, choices=[(0, 'Attended'), (1, 'Absent (Explained)'), (2, 'Absent (Unexplained'), (3, 'Integrating')], default=0)),
                ('thursday_arrived', models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 AM'), (datetime.time(9, 30), '9:30 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(10, 30), '10:30 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(13, 30), '1:30 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(14, 30), '2:30 PM')], default=(datetime.time(9, 0), '9:00 AM'))),
                ('friday_points', models.IntegerField(blank=True, default=100)),
                ('friday_attended', models.IntegerField(blank=True, choices=[(0, 'Attended'), (1, 'Absent (Explained)'), (2, 'Absent (Unexplained'), (3, 'Integrating')], default=0)),
                ('friday_arrived', models.TimeField(blank=True, choices=[(datetime.time(9, 0), '9:00 AM'), (datetime.time(9, 30), '9:30 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(10, 30), '10:30 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(13, 0), '1:00 PM'), (datetime.time(13, 30), '1:30 PM'), (datetime.time(14, 0), '2:00 PM'), (datetime.time(14, 30), '2:30 PM')], default=(datetime.time(9, 0), '9:00 AM'))),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('class_name', models.CharField(choices=[('', ''), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6')], default='C1', max_length=10)),
                ('year', models.IntegerField(choices=[(7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('enrolled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wio_type', models.CharField(choices=[('', '--------'), ('System', 'System'), ('Instant', 'Instant')], max_length=10)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Student')),
            ],
        ),
        migrations.AddField(
            model_name='behaviourtracking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Student'),
        ),
    ]
