# Generated by Django 2.0 on 2018-03-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20180302_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behaviourtracking',
            name='friday_points',
        ),
        migrations.RemoveField(
            model_name='behaviourtracking',
            name='monday_points',
        ),
        migrations.RemoveField(
            model_name='behaviourtracking',
            name='thursday_points',
        ),
        migrations.RemoveField(
            model_name='behaviourtracking',
            name='tuesday_points',
        ),
        migrations.RemoveField(
            model_name='behaviourtracking',
            name='wednesday_points',
        ),
        migrations.AddField(
            model_name='behaviourtracking',
            name='friday',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='behaviourtracking',
            name='monday',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='behaviourtracking',
            name='thursday',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='behaviourtracking',
            name='tuesday',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='behaviourtracking',
            name='wednesday',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
