# Generated by Django 2.0 on 2018-03-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20180302_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviourtracking',
            name='friday',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='monday',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='thursday',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='tuesday',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='wednesday',
            field=models.IntegerField(blank=True),
        ),
    ]
