# Generated by Django 2.0 on 2018-03-09 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20180302_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='behaviourtracking',
            old_name='friday',
            new_name='friday_points',
        ),
        migrations.RenameField(
            model_name='behaviourtracking',
            old_name='monday',
            new_name='monday_points',
        ),
        migrations.RenameField(
            model_name='behaviourtracking',
            old_name='thursday',
            new_name='thursday_points',
        ),
        migrations.RenameField(
            model_name='behaviourtracking',
            old_name='tuesday',
            new_name='tuesday_points',
        ),
        migrations.RenameField(
            model_name='behaviourtracking',
            old_name='wednesday',
            new_name='wednesday_points',
        ),
    ]
