# Generated by Django 2.0 on 2018-03-09 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20180309_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitout',
            name='student',
        ),
        migrations.DeleteModel(
            name='WorkItOut',
        ),
    ]
