# Generated by Django 2.0 on 2018-03-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20180309_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviourtracking',
            name='friday_attended',
            field=models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended')], default=0),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='monday_attended',
            field=models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended')], default=0),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='thursday_attended',
            field=models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended')], default=0),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='tuesday_attended',
            field=models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended')], default=0),
        ),
        migrations.AlterField(
            model_name='behaviourtracking',
            name='wednesday_attended',
            field=models.IntegerField(choices=[(1, 'Attended'), (2, 'Absent (Explained)'), (3, 'Absent (Unexplained'), (4, 'Integrating'), (5, 'Suspended')], default=0),
        ),
    ]
