# Generated by Django 2.0.3 on 2018-04-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('class_name', models.CharField(choices=[('', ''), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6')], default='C1', max_length=10)),
                ('year', models.IntegerField(choices=[(7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('enrolled', models.BooleanField(default=False)),
            ],
        ),
    ]
