# Generated by Django 2.0.5 on 2018-05-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled',
            field=models.BooleanField(default=True),
        ),
    ]
