# Generated by Django 2.0.2 on 2018-05-09 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20180504_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enrolled',
            new_name='enroled',
        ),
    ]
