# Generated by Django 2.1 on 2018-10-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_auto_20180509_0441'),
        ('console', '0002_auto_20180829_0156'),
    ]

    operations = [
    ]
