# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('file_obj', models.FileField(upload_to='ASR')),
            ],
            options={
                'verbose_name': 'Annual School Report',
                'verbose_name_plural': 'Annual School Reports',
            },
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
    ]
