# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171024_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='name',
        ),
    ]
