# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_newsletter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asr',
            name='name',
        ),
    ]
