# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_asr_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='permission_slip',
            field=models.FileField(blank=True, default=None, null=True, upload_to='permission_slips'),
        ),
    ]
