# Generated by Django 2.0.2 on 2018-11-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
    ]
