# Generated by Django 2.0.2 on 2018-11-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20181128_2343'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publication',
            table='main_publication',
        ),
    ]
