# Generated by Django 2.0.2 on 2018-11-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20181129_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'publication'},
        ),
    ]
